version: "3.8"
services:
  web:
    image: processmaker/pm4-core:${PM_VERSION}
    ports:
      - ${PM_APP_PORT}:80
      - ${PM_BROADCASTER_PORT}:6001
    environment:
      - PM_APP_URL
      - PM_APP_PORT
      - PM_BROADCASTER_PORT
    volumes:
      - ${PM_DOCKER_SOCK}:/var/run/docker.sock
      - storage:/code/pm4/storage
    links:
      - redis
      - mysql
    depends_on:
      - mysql
      - redis
    networks:
      - common_network

  redis:
    image: redis
    networks:
      - common_network

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password 
      MYSQL_DATABASE: processmaker
      MYSQL_USER: pm
      MYSQL_PASSWORD: pass
    volumes:
      - database:/var/lib/mysql
    networks:
      - common_network

networks:
  common_network:
    driver: bridge

volumes:
  database:
  storage:

